<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Data Injection_button2</name>
   <tag></tag>
   <elementGuidId>22069e00-97f9-481d-b558-e2d781bf0f09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8b6e190-41aa-4442-a561-7ffc179144c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button2</value>
      <webElementGuid>caff2ec8-04ff-4946-b355-dbfe19983a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>a95593bf-d8c9-470d-86d0-26d7e5d57645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>28c87308-10a2-43af-b561-3f249f5875b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltip</name>
      <type>Main</type>
      <value>Tambah Data</value>
      <webElementGuid>0bb9d48d-9099-4850-a376-48c2de598095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>67faac7c-7aa6-4b22-85b8-e734eb6807e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-tooltip-trigger ml-4 mat-mini-fab mat-button-base mat-primary cdk-focused cdk-mouse-focused</value>
      <webElementGuid>0358e9bb-f9c7-410f-86fa-9e126d470a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>92aaacb2-6ccf-4f4e-91fd-26e8886f41b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>84d8439b-5ce8-49c3-9553-3160030eafea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-message</name>
      <type>Main</type>
      <value>Tambah Data</value>
      <webElementGuid>f3bc603c-1b91-4a3b-ad96-1118af1101bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e297579b-9b73-41d9-8c5b-fdbf1981b6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-717</value>
      <webElementGuid>06e221d7-63b1-4ce1-b4f2-8e0204458f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>add-edit-data-injection</value>
      <webElementGuid>4f042a2e-1732-454a-9b2e-af41721e358e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-query-params</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>0bb2c13d-ca5a-45ad-a64e-5ce236444ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button2&quot;)</value>
      <webElementGuid>3f61e96b-77cc-468f-8da8-1a6cd0f46132</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button2']</value>
      <webElementGuid>5660dd9e-0025-44c4-936e-ce78cf198e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Injection'])[4]/following::button[2]</value>
      <webElementGuid>9f3d1e2a-16dd-435a-a803-8e76a86f02b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Injection'])[3]/following::button[2]</value>
      <webElementGuid>87160a39-96d6-4139-bd7e-fceff30736e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aksi'])[1]/preceding::button[1]</value>
      <webElementGuid>297e049e-3ea8-4e5a-baf9-cb90bbe728a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank'])[2]/preceding::button[1]</value>
      <webElementGuid>3da02685-ddfd-4c57-a49e-3ac3ce61d417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>afbbd3f5-4f23-4562-82d0-7b290026b84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button2' and @type = 'button']</value>
      <webElementGuid>1f0cae41-7df9-4b5a-9cc0-49e03e07dd2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
