<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag and drop files or click here</name>
   <tag></tag>
   <elementGuidId>f1d9a143-6797-4d15-9973-72093f47fabc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.upload-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Template'])[1]/following::div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f989f58-0317-462b-a98e-df1baa8d74d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-text</value>
      <webElementGuid>8056de31-5413-4935-b345-9cb41450ae0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag and drop files or click here </value>
      <webElementGuid>e0c68bdc-f245-4cae-bde7-0cea52c159ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;vex-style-default ng-tns-0-0 is-blink vex-layout-ares&quot;]/vex-root[1]/vex-custom-layout[@class=&quot;ng-star-inserted&quot;]/vex-layout[1]/div[@class=&quot;page-container horizontal-layout is-mobile has-fixed-footer has-footer toolbar-fixed&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content sidenav-content&quot;]/main[@class=&quot;content&quot;]/vex-add-edit-data-injection[@class=&quot;ng-star-inserted&quot;]/vex-page-layout[@class=&quot;vex-page-layout vex-page-layout-simple&quot;]/vex-page-layout-content[@class=&quot;vex-page-layout-content&quot;]/div[@class=&quot;card&quot;]/div[1]/div[1]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;px-6 py-6&quot;]/div[1]/div[@class=&quot;file-upload mb-6 sm:px-0 md:px-4 lg:px-4 xl:px-4 ng-star-inserted&quot;]/file-upload[@class=&quot;ng-tns-c418-751 ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/label[@class=&quot;upload-input ng-tns-c418-751 ng-trigger ng-trigger-zoomAnimation&quot;]/file-upload-drop-zone[@class=&quot;ng-tns-c418-751 ng-star-inserted&quot;]/div[@class=&quot;upload-text&quot;]</value>
      <webElementGuid>4f6b23c7-7df1-4930-83e2-5b1165f1fde2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Template'])[1]/following::div[2]</value>
      <webElementGuid>a75f6a28-3579-450e-911b-8d9d25fe02cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='files']/parent::*</value>
      <webElementGuid>da108c97-43fb-49cf-a7b2-23a5a46e6de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//file-upload-drop-zone/div[2]</value>
      <webElementGuid>d147f496-fb51-4614-b6cc-af82891f87ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Drag and drop files or click here ' or . = 'Drag and drop files or click here ')]</value>
      <webElementGuid>b5fd77f9-6470-4aea-a15a-9cbea27e73df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
