<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Laboratorium Resolusi</name>
   <tag></tag>
   <elementGuidId>dfe022e7-3ee2-438d-94ec-e29c25e9d125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-tooltip-trigger.item-label.ng-tns-c167-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu492']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fce6969a-90ec-4481-ba60-a01dfdad2c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f351c150-b3ef-4b77-ac01-a17971054b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-tooltip-trigger item-label ng-tns-c167-18</value>
      <webElementGuid>4a9ee4a2-30a5-4e2a-9c39-44706d1a193c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>bd0a6a56-3e2f-4491-a0fb-889e0cb47acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-message</name>
      <type>Main</type>
      <value>Laboratorium Resolusi</value>
      <webElementGuid>d57121a1-29a6-4086-8379-ff64d0192910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-679</value>
      <webElementGuid>8ce18e9f-e893-409c-a22a-b6de1b9002f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Laboratorium Resolusi</value>
      <webElementGuid>dfd2c647-79b4-48a6-baa7-aa75095f3c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu492&quot;)/span[@class=&quot;mat-tooltip-trigger item-label ng-tns-c167-18&quot;]</value>
      <webElementGuid>f4ba9943-ffa1-41a2-b8bc-04014c1fc460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu492']/span</value>
      <webElementGuid>f46f8d75-6068-4d8d-880a-de8af2c74094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil Publikasi'])[1]/following::span[1]</value>
      <webElementGuid>7fcd53fb-9c0b-4d77-b273-7a14bb05954c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Publikasi'])[1]/following::span[2]</value>
      <webElementGuid>659a228e-4a0f-47af-b238-a0fb17e98f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proteksi data'])[1]/preceding::span[1]</value>
      <webElementGuid>cea3b309-b853-4daa-984c-069d5bce7309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waktu Resolusi'])[1]/preceding::span[2]</value>
      <webElementGuid>875528c0-cbb6-4a8c-bbe3-bc28e94873b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Laboratorium Resolusi']/parent::*</value>
      <webElementGuid>cab14c34-82b8-47f7-ad26-1b299a420e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//vex-sidenav-item[9]/div/span</value>
      <webElementGuid>7d103d83-2a4e-4524-9196-a8587aea6695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Laboratorium Resolusi' or . = 'Laboratorium Resolusi')]</value>
      <webElementGuid>796b6e77-644b-4a17-9267-e3a009eff7b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
