<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ICS DEV - ICS.DEV01lps.go.id</name>
   <tag></tag>
   <elementGuidId>df89c852-20c9-4697-a079-0ebb7dacd038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-260']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e5b59670-4b2f-4761-82be-422305a52b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>b01d37da-cade-4ad7-99c9-a09a3a866305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ICS DEV - ICS.DEV01@lps.go.id </value>
      <webElementGuid>95c95257-f1db-47e8-91b7-1d9500a65893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-260&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>3c7e1cc2-f207-4405-a944-68e433704a2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-260']/span</value>
      <webElementGuid>51a1f4b6-bc14-4454-a751-67a68c6e1767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DES 2021'])[1]/following::span[1]</value>
      <webElementGuid>330fa01b-5cfc-4f77-a040-61fe57c2c14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-option-260', '&quot;', ')/span[@class=', '&quot;', 'mat-option-text', '&quot;', ']')])[1]/following::span[1]</value>
      <webElementGuid>8fd909bd-1553-4c9f-8e0e-007d95b093a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ICS DEV 02 - ICS.DEV02@lps.go.id'])[1]/preceding::span[1]</value>
      <webElementGuid>545fa217-0780-48e2-b08b-4e8695548921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ICS DEV 03 - ICS.DEV03@lps.go.id'])[1]/preceding::span[2]</value>
      <webElementGuid>6f552994-b4b2-4ca4-92ac-5c05f1db2010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ICS DEV - ICS.DEV01@lps.go.id']/parent::*</value>
      <webElementGuid>845aa4ac-092d-4861-8e5f-92acf60a0173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option/span</value>
      <webElementGuid>f15f464c-652a-4754-a782-12bcd2ccf522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' ICS DEV - ICS.DEV01@lps.go.id ' or . = ' ICS DEV - ICS.DEV01@lps.go.id ')]</value>
      <webElementGuid>9fa53b02-fb34-480c-9232-f7105a6ad64f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
