<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonUpload</name>
   <tag></tag>
   <elementGuidId>aabc21a0-789b-4127-9b8c-571b9a0569ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//INPUT[@name='upload_file']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
